name: PR Validation and Auto-formatting

on:
  pull_request:

jobs:
  auto-format:
    name: Auto-format and Push Changes
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install tools (black and isort)
      - name: Install Tools
        run: |
          echo "Installing tools..."
          python -m pip install --upgrade pip
          pip install black isort

      # Step 4: Run black and isort to format the code
      - name: Run Black and isort
        run: |
          echo "Running black..."
          black --line-length=119 .
          echo "Running isort..."
          isort .

      # Step 5: Commit and push changes if any files were modified
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Configuring git user..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "Checking for changes..."
          git status

          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Staging files..."
            git add .

            echo "Committing changes..."
            git commit -m "Auto-format code with Black and isort"

            echo "Pushing changes to the branch..."
            git push origin ${{ github.head_ref }}
            echo "Push completed successfully."
          else
            echo "No changes detected. Nothing to commit or push."
          fi
